/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessLevel = { 'VIP' : null } |
  { 'Premium' : null } |
  { 'Free' : null } |
  { 'Basic' : null };
export type Category = { 'AI' : null } |
  { 'General' : null } |
  { 'Crypto' : null };
export interface ContractConfig {
  'nftVipAddress' : string,
  'vipThreshold' : bigint,
  'nftBasicAddress' : string,
  'basicThreshold' : bigint,
  'premiumThreshold' : bigint,
  'coinXAddress' : string,
  'nftPremiumAddress' : string,
}
export interface NewsletterSub {
  'subscribedAt' : bigint,
  'email' : string,
  'isConfirmed' : boolean,
}
export interface Page {
  'title' : string,
  'content' : string,
  'slug' : string,
  'isVisible' : boolean,
}
export interface PlanConfig {
  'purchaseLinkNFT' : string,
  'usdPrice' : bigint,
  'purchaseLinkCoinX' : string,
  'nftContractAddress' : string,
  'coinXThreshold' : bigint,
  'purchaseLinkPaypal' : string,
}
export interface RegionConfig {
  'defaultLanguages' : Array<string>,
  'supportedLanguageCodes' : Array<string>,
  'arabicCountryCodes' : Array<string>,
}
export interface T {
  'id' : string,
  'accessLevel' : AccessLevel,
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'language' : string,
  'summary' : string,
  'isArabicOriginal' : boolean,
  'isVisible' : boolean,
  'category' : Category,
}
export interface TickerEntry {
  'change24h' : bigint,
  'price' : bigint,
  'symbol' : string,
}
export interface WalletSession {
  'walletType' : string,
  'walletAddress' : string,
  'connectedAt' : bigint,
  'detectedMembershipLevel' : AccessLevel,
}
export interface _SERVICE {
  'addArticle' : ActorMethod<[T], undefined>,
  'addNewsletterSubscriber' : ActorMethod<[string], undefined>,
  'addOrUpdatePage' : ActorMethod<[Page], undefined>,
  'addOrUpdateTicker' : ActorMethod<[TickerEntry], undefined>,
  'confirmNewsletterSubscriber' : ActorMethod<[string], undefined>,
  'getAllNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSub>>,
  'getAllPages' : ActorMethod<[], Array<Page>>,
  'getAllTickers' : ActorMethod<[], Array<TickerEntry>>,
  'getAllWalletSessions' : ActorMethod<[], Array<WalletSession>>,
  'getArticle' : ActorMethod<[string], T>,
  'getArticlesByAccessLevel' : ActorMethod<[AccessLevel], Array<T>>,
  'getArticlesByCategory' : ActorMethod<[Category], Array<T>>,
  'getContractConfig' : ActorMethod<[], ContractConfig>,
  'getHomepageArticles' : ActorMethod<
    [],
    {
      'vip' : Array<T>,
      'premium' : Array<T>,
      'free' : Array<T>,
      'basic' : Array<T>,
    }
  >,
  'getLatestArticlesByAccessLevel' : ActorMethod<
    [AccessLevel, bigint],
    Array<T>
  >,
  'getPage' : ActorMethod<[string], Page>,
  'getPlanConfigs' : ActorMethod<[], Array<PlanConfig>>,
  'getRegionConfig' : ActorMethod<[], RegionConfig>,
  'getTicker' : ActorMethod<[string], TickerEntry>,
  'getWalletSession' : ActorMethod<[string], WalletSession>,
  'recordWalletSession' : ActorMethod<[string, string, AccessLevel], undefined>,
  'seedPlaceholderPages' : ActorMethod<[], undefined>,
  'updateContractConfig' : ActorMethod<[ContractConfig], undefined>,
  'updatePlanConfig' : ActorMethod<[string, PlanConfig], undefined>,
  'updateRegionConfig' : ActorMethod<[RegionConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];