/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccessLevel = IDL.Variant({
  'VIP' : IDL.Null,
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
  'Basic' : IDL.Null,
});
export const Category = IDL.Variant({
  'AI' : IDL.Null,
  'General' : IDL.Null,
  'Crypto' : IDL.Null,
});
export const T = IDL.Record({
  'id' : IDL.Text,
  'accessLevel' : AccessLevel,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'language' : IDL.Text,
  'summary' : IDL.Text,
  'isArabicOriginal' : IDL.Bool,
  'isVisible' : IDL.Bool,
  'category' : Category,
});
export const Page = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const TickerEntry = IDL.Record({
  'change24h' : IDL.Int,
  'price' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const NewsletterSub = IDL.Record({
  'subscribedAt' : IDL.Int,
  'email' : IDL.Text,
  'isConfirmed' : IDL.Bool,
});
export const WalletSession = IDL.Record({
  'walletType' : IDL.Text,
  'walletAddress' : IDL.Text,
  'connectedAt' : IDL.Int,
  'detectedMembershipLevel' : AccessLevel,
});
export const ContractConfig = IDL.Record({
  'nftVipAddress' : IDL.Text,
  'vipThreshold' : IDL.Nat,
  'nftBasicAddress' : IDL.Text,
  'basicThreshold' : IDL.Nat,
  'premiumThreshold' : IDL.Nat,
  'coinXAddress' : IDL.Text,
  'nftPremiumAddress' : IDL.Text,
});
export const PlanConfig = IDL.Record({
  'purchaseLinkNFT' : IDL.Text,
  'usdPrice' : IDL.Nat,
  'purchaseLinkCoinX' : IDL.Text,
  'nftContractAddress' : IDL.Text,
  'coinXThreshold' : IDL.Nat,
  'purchaseLinkPaypal' : IDL.Text,
});
export const RegionConfig = IDL.Record({
  'defaultLanguages' : IDL.Vec(IDL.Text),
  'supportedLanguageCodes' : IDL.Vec(IDL.Text),
  'arabicCountryCodes' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addArticle' : IDL.Func([T], [], []),
  'addNewsletterSubscriber' : IDL.Func([IDL.Text], [], []),
  'addOrUpdatePage' : IDL.Func([Page], [], []),
  'addOrUpdateTicker' : IDL.Func([TickerEntry], [], []),
  'confirmNewsletterSubscriber' : IDL.Func([IDL.Text], [], ['query']),
  'getAllNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSub)],
      ['query'],
    ),
  'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
  'getAllTickers' : IDL.Func([], [IDL.Vec(TickerEntry)], ['query']),
  'getAllWalletSessions' : IDL.Func([], [IDL.Vec(WalletSession)], ['query']),
  'getArticle' : IDL.Func([IDL.Text], [T], ['query']),
  'getArticlesByAccessLevel' : IDL.Func([AccessLevel], [IDL.Vec(T)], ['query']),
  'getArticlesByCategory' : IDL.Func([Category], [IDL.Vec(T)], ['query']),
  'getContractConfig' : IDL.Func([], [ContractConfig], ['query']),
  'getHomepageArticles' : IDL.Func(
      [],
      [
        IDL.Record({
          'vip' : IDL.Vec(T),
          'premium' : IDL.Vec(T),
          'free' : IDL.Vec(T),
          'basic' : IDL.Vec(T),
        }),
      ],
      ['query'],
    ),
  'getLatestArticlesByAccessLevel' : IDL.Func(
      [AccessLevel, IDL.Nat],
      [IDL.Vec(T)],
      ['query'],
    ),
  'getPage' : IDL.Func([IDL.Text], [Page], ['query']),
  'getPlanConfigs' : IDL.Func([], [IDL.Vec(PlanConfig)], ['query']),
  'getRegionConfig' : IDL.Func([], [RegionConfig], ['query']),
  'getTicker' : IDL.Func([IDL.Text], [TickerEntry], ['query']),
  'getWalletSession' : IDL.Func([IDL.Text], [WalletSession], ['query']),
  'recordWalletSession' : IDL.Func([IDL.Text, IDL.Text, AccessLevel], [], []),
  'seedPlaceholderPages' : IDL.Func([], [], []),
  'updateContractConfig' : IDL.Func([ContractConfig], [], []),
  'updatePlanConfig' : IDL.Func([IDL.Text, PlanConfig], [], []),
  'updateRegionConfig' : IDL.Func([RegionConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccessLevel = IDL.Variant({
    'VIP' : IDL.Null,
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
    'Basic' : IDL.Null,
  });
  const Category = IDL.Variant({
    'AI' : IDL.Null,
    'General' : IDL.Null,
    'Crypto' : IDL.Null,
  });
  const T = IDL.Record({
    'id' : IDL.Text,
    'accessLevel' : AccessLevel,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'language' : IDL.Text,
    'summary' : IDL.Text,
    'isArabicOriginal' : IDL.Bool,
    'isVisible' : IDL.Bool,
    'category' : Category,
  });
  const Page = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const TickerEntry = IDL.Record({
    'change24h' : IDL.Int,
    'price' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const NewsletterSub = IDL.Record({
    'subscribedAt' : IDL.Int,
    'email' : IDL.Text,
    'isConfirmed' : IDL.Bool,
  });
  const WalletSession = IDL.Record({
    'walletType' : IDL.Text,
    'walletAddress' : IDL.Text,
    'connectedAt' : IDL.Int,
    'detectedMembershipLevel' : AccessLevel,
  });
  const ContractConfig = IDL.Record({
    'nftVipAddress' : IDL.Text,
    'vipThreshold' : IDL.Nat,
    'nftBasicAddress' : IDL.Text,
    'basicThreshold' : IDL.Nat,
    'premiumThreshold' : IDL.Nat,
    'coinXAddress' : IDL.Text,
    'nftPremiumAddress' : IDL.Text,
  });
  const PlanConfig = IDL.Record({
    'purchaseLinkNFT' : IDL.Text,
    'usdPrice' : IDL.Nat,
    'purchaseLinkCoinX' : IDL.Text,
    'nftContractAddress' : IDL.Text,
    'coinXThreshold' : IDL.Nat,
    'purchaseLinkPaypal' : IDL.Text,
  });
  const RegionConfig = IDL.Record({
    'defaultLanguages' : IDL.Vec(IDL.Text),
    'supportedLanguageCodes' : IDL.Vec(IDL.Text),
    'arabicCountryCodes' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addArticle' : IDL.Func([T], [], []),
    'addNewsletterSubscriber' : IDL.Func([IDL.Text], [], []),
    'addOrUpdatePage' : IDL.Func([Page], [], []),
    'addOrUpdateTicker' : IDL.Func([TickerEntry], [], []),
    'confirmNewsletterSubscriber' : IDL.Func([IDL.Text], [], ['query']),
    'getAllNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSub)],
        ['query'],
      ),
    'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
    'getAllTickers' : IDL.Func([], [IDL.Vec(TickerEntry)], ['query']),
    'getAllWalletSessions' : IDL.Func([], [IDL.Vec(WalletSession)], ['query']),
    'getArticle' : IDL.Func([IDL.Text], [T], ['query']),
    'getArticlesByAccessLevel' : IDL.Func(
        [AccessLevel],
        [IDL.Vec(T)],
        ['query'],
      ),
    'getArticlesByCategory' : IDL.Func([Category], [IDL.Vec(T)], ['query']),
    'getContractConfig' : IDL.Func([], [ContractConfig], ['query']),
    'getHomepageArticles' : IDL.Func(
        [],
        [
          IDL.Record({
            'vip' : IDL.Vec(T),
            'premium' : IDL.Vec(T),
            'free' : IDL.Vec(T),
            'basic' : IDL.Vec(T),
          }),
        ],
        ['query'],
      ),
    'getLatestArticlesByAccessLevel' : IDL.Func(
        [AccessLevel, IDL.Nat],
        [IDL.Vec(T)],
        ['query'],
      ),
    'getPage' : IDL.Func([IDL.Text], [Page], ['query']),
    'getPlanConfigs' : IDL.Func([], [IDL.Vec(PlanConfig)], ['query']),
    'getRegionConfig' : IDL.Func([], [RegionConfig], ['query']),
    'getTicker' : IDL.Func([IDL.Text], [TickerEntry], ['query']),
    'getWalletSession' : IDL.Func([IDL.Text], [WalletSession], ['query']),
    'recordWalletSession' : IDL.Func([IDL.Text, IDL.Text, AccessLevel], [], []),
    'seedPlaceholderPages' : IDL.Func([], [], []),
    'updateContractConfig' : IDL.Func([ContractConfig], [], []),
    'updatePlanConfig' : IDL.Func([IDL.Text, PlanConfig], [], []),
    'updateRegionConfig' : IDL.Func([RegionConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };