/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContractConfig {
    nftVipAddress: string;
    vipThreshold: bigint;
    nftBasicAddress: string;
    basicThreshold: bigint;
    premiumThreshold: bigint;
    coinXAddress: string;
    nftPremiumAddress: string;
}
export interface RegionConfig {
    defaultLanguages: Array<string>;
    supportedLanguageCodes: Array<string>;
    arabicCountryCodes: Array<string>;
}
export interface T {
    id: string;
    accessLevel: AccessLevel;
    title: string;
    content: string;
    publishDate: bigint;
    language: string;
    summary: string;
    isArabicOriginal: boolean;
    isVisible: boolean;
    category: Category;
}
export interface Page {
    title: string;
    content: string;
    slug: string;
    isVisible: boolean;
}
export interface WalletSession {
    walletType: string;
    walletAddress: string;
    connectedAt: bigint;
    detectedMembershipLevel: AccessLevel;
}
export interface TickerEntry {
    change24h: bigint;
    price: bigint;
    symbol: string;
}
export interface NewsletterSub {
    subscribedAt: bigint;
    email: string;
    isConfirmed: boolean;
}
export interface PlanConfig {
    purchaseLinkNFT: string;
    usdPrice: bigint;
    purchaseLinkCoinX: string;
    nftContractAddress: string;
    coinXThreshold: bigint;
    purchaseLinkPaypal: string;
}
export enum AccessLevel {
    VIP = "VIP",
    Premium = "Premium",
    Free = "Free",
    Basic = "Basic"
}
export enum Category {
    AI = "AI",
    General = "General",
    Crypto = "Crypto"
}
export interface backendInterface {
    addArticle(article: T): Promise<void>;
    addNewsletterSubscriber(email: string): Promise<void>;
    addOrUpdatePage(page: Page): Promise<void>;
    addOrUpdateTicker(ticker: TickerEntry): Promise<void>;
    confirmNewsletterSubscriber(email: string): Promise<void>;
    getAllNewsletterSubscribers(): Promise<Array<NewsletterSub>>;
    getAllPages(): Promise<Array<Page>>;
    getAllTickers(): Promise<Array<TickerEntry>>;
    getAllWalletSessions(): Promise<Array<WalletSession>>;
    getArticle(id: string): Promise<T>;
    getArticlesByAccessLevel(level: AccessLevel): Promise<Array<T>>;
    getArticlesByCategory(category: Category): Promise<Array<T>>;
    getContractConfig(): Promise<ContractConfig>;
    getHomepageArticles(): Promise<{
        vip: Array<T>;
        premium: Array<T>;
        free: Array<T>;
        basic: Array<T>;
    }>;
    getLatestArticlesByAccessLevel(level: AccessLevel, maxCount: bigint): Promise<Array<T>>;
    getPage(slug: string): Promise<Page>;
    getPlanConfigs(): Promise<Array<PlanConfig>>;
    getRegionConfig(): Promise<RegionConfig>;
    getTicker(symbol: string): Promise<TickerEntry>;
    getWalletSession(address: string): Promise<WalletSession>;
    recordWalletSession(address: string, wtype: string, detectedLevel: AccessLevel): Promise<void>;
    seedPlaceholderPages(): Promise<void>;
    updateContractConfig(config: ContractConfig): Promise<void>;
    updatePlanConfig(planName: string, config: PlanConfig): Promise<void>;
    updateRegionConfig(config: RegionConfig): Promise<void>;
}
import type { AccessLevel as _AccessLevel, Category as _Category, T as _T, WalletSession as _WalletSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addArticle(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addArticle(to_candid_T_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArticle(to_candid_T_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNewsletterSubscriber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsletterSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsletterSubscriber(arg0);
            return result;
        }
    }
    async addOrUpdatePage(arg0: Page): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePage(arg0);
            return result;
        }
    }
    async addOrUpdateTicker(arg0: TickerEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTicker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTicker(arg0);
            return result;
        }
    }
    async confirmNewsletterSubscriber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmNewsletterSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmNewsletterSubscriber(arg0);
            return result;
        }
    }
    async getAllNewsletterSubscribers(): Promise<Array<NewsletterSub>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsletterSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsletterSubscribers();
            return result;
        }
    }
    async getAllPages(): Promise<Array<Page>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPages();
            return result;
        }
    }
    async getAllTickers(): Promise<Array<TickerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTickers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTickers();
            return result;
        }
    }
    async getAllWalletSessions(): Promise<Array<WalletSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWalletSessions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWalletSessions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticle(arg0: string): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_T_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_T_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByAccessLevel(arg0: AccessLevel): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByAccessLevel(to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByAccessLevel(to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByCategory(arg0: Category): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractConfig(): Promise<ContractConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractConfig();
            return result;
        }
    }
    async getHomepageArticles(): Promise<{
        vip: Array<T>;
        premium: Array<T>;
        free: Array<T>;
        basic: Array<T>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageArticles();
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageArticles();
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestArticlesByAccessLevel(arg0: AccessLevel, arg1: bigint): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestArticlesByAccessLevel(to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestArticlesByAccessLevel(to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPage(arg0: string): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getPage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPage(arg0);
            return result;
        }
    }
    async getPlanConfigs(): Promise<Array<PlanConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanConfigs();
            return result;
        }
    }
    async getRegionConfig(): Promise<RegionConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegionConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegionConfig();
            return result;
        }
    }
    async getTicker(arg0: string): Promise<TickerEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicker(arg0);
            return result;
        }
    }
    async getWalletSession(arg0: string): Promise<WalletSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletSession(arg0);
                return from_candid_WalletSession_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletSession(arg0);
            return from_candid_WalletSession_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordWalletSession(arg0: string, arg1: string, arg2: AccessLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWalletSession(arg0, arg1, to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWalletSession(arg0, arg1, to_candid_AccessLevel_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async seedPlaceholderPages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPlaceholderPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPlaceholderPages();
            return result;
        }
    }
    async updateContractConfig(arg0: ContractConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContractConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContractConfig(arg0);
            return result;
        }
    }
    async updatePlanConfig(arg0: string, arg1: PlanConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlanConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlanConfig(arg0, arg1);
            return result;
        }
    }
    async updateRegionConfig(arg0: RegionConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegionConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegionConfig(arg0);
            return result;
        }
    }
}
function from_candid_AccessLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessLevel): AccessLevel {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_T_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WalletSession_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletSession): WalletSession {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    accessLevel: _AccessLevel;
    title: string;
    content: string;
    publishDate: bigint;
    language: string;
    summary: string;
    isArabicOriginal: boolean;
    isVisible: boolean;
    category: _Category;
}): {
    id: string;
    accessLevel: AccessLevel;
    title: string;
    content: string;
    publishDate: bigint;
    language: string;
    summary: string;
    isArabicOriginal: boolean;
    isVisible: boolean;
    category: Category;
} {
    return {
        id: value.id,
        accessLevel: from_candid_AccessLevel_n10(_uploadFile, _downloadFile, value.accessLevel),
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        language: value.language,
        summary: value.summary,
        isArabicOriginal: value.isArabicOriginal,
        isVisible: value.isVisible,
        category: from_candid_Category_n14(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vip: Array<_T>;
    premium: Array<_T>;
    free: Array<_T>;
    basic: Array<_T>;
}): {
    vip: Array<T>;
    premium: Array<T>;
    free: Array<T>;
    basic: Array<T>;
} {
    return {
        vip: from_candid_vec_n16(_uploadFile, _downloadFile, value.vip),
        premium: from_candid_vec_n16(_uploadFile, _downloadFile, value.premium),
        free: from_candid_vec_n16(_uploadFile, _downloadFile, value.free),
        basic: from_candid_vec_n16(_uploadFile, _downloadFile, value.basic)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walletType: string;
    walletAddress: string;
    connectedAt: bigint;
    detectedMembershipLevel: _AccessLevel;
}): {
    walletType: string;
    walletAddress: string;
    connectedAt: bigint;
    detectedMembershipLevel: AccessLevel;
} {
    return {
        walletType: value.walletType,
        walletAddress: value.walletAddress,
        connectedAt: value.connectedAt,
        detectedMembershipLevel: from_candid_AccessLevel_n10(_uploadFile, _downloadFile, value.detectedMembershipLevel)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VIP: null;
} | {
    Premium: null;
} | {
    Free: null;
} | {
    Basic: null;
}): AccessLevel {
    return "VIP" in value ? AccessLevel.VIP : "Premium" in value ? AccessLevel.Premium : "Free" in value ? AccessLevel.Free : "Basic" in value ? AccessLevel.Basic : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AI: null;
} | {
    General: null;
} | {
    Crypto: null;
}): Category {
    return "AI" in value ? Category.AI : "General" in value ? Category.General : "Crypto" in value ? Category.Crypto : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletSession>): Array<WalletSession> {
    return value.map((x)=>from_candid_WalletSession_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AccessLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccessLevel): _AccessLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_T_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    accessLevel: AccessLevel;
    title: string;
    content: string;
    publishDate: bigint;
    language: string;
    summary: string;
    isArabicOriginal: boolean;
    isVisible: boolean;
    category: Category;
}): {
    id: string;
    accessLevel: _AccessLevel;
    title: string;
    content: string;
    publishDate: bigint;
    language: string;
    summary: string;
    isArabicOriginal: boolean;
    isVisible: boolean;
    category: _Category;
} {
    return {
        id: value.id,
        accessLevel: to_candid_AccessLevel_n3(_uploadFile, _downloadFile, value.accessLevel),
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        language: value.language,
        summary: value.summary,
        isArabicOriginal: value.isArabicOriginal,
        isVisible: value.isVisible,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccessLevel): {
    VIP: null;
} | {
    Premium: null;
} | {
    Free: null;
} | {
    Basic: null;
} {
    return value == AccessLevel.VIP ? {
        VIP: null
    } : value == AccessLevel.Premium ? {
        Premium: null
    } : value == AccessLevel.Free ? {
        Free: null
    } : value == AccessLevel.Basic ? {
        Basic: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    AI: null;
} | {
    General: null;
} | {
    Crypto: null;
} {
    return value == Category.AI ? {
        AI: null
    } : value == Category.General ? {
        General: null
    } : value == Category.Crypto ? {
        Crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
